language: python
python:
    - "3.8"

install:
    - pip3 install -r requirements.txt
    - pip3 install .
    - pip3 install tox

script:
    - cd exma/boundary
      make clean && make
      cd ../cluster
      make clean && make
      cd ../cn
      make clean && make
      cd ../en
      make clean && make
      cd ../rdf
      make clean && make
      cd ../../
    - tox
